# Generated by Django 4.0 on 2023-04-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0002_alter_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='videonews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'videonews',
            },
        ),
    ]
