# Generated by Django 4.0 on 2023-05-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news1', '0006_rename_category_videonews_categoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('newsid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='news1.news')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
