# Generated by Django 4.0 on 2023-05-27 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news1', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='userid',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
