# Generated by Django 4.0 on 2023-05-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0008_news_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
